import { Teacher, Class, Student, Announcement, FAQ, Setting, ActivityLog } from '../types/database.types';

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 't-1',
    name: 'Drs. H. Maman Suherman, M.Pd.',
    nip: '196805121993031004',
    phone: '081234567890',
    email: 'maman.suherman@sman1bdg.sch.id',
    subject: 'Fisika',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't-2',
    name: 'Dra. Hj. Neneng Hasanah, M.Si.',
    nip: '197210151998022001',
    phone: '081398765432',
    email: 'neneng.hasanah@sman1bdg.sch.id',
    subject: 'Matematika Peminatan',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't-3',
    name: 'Budi Raharjo, S.Pd.',
    nip: '198204212009011003',
    phone: '082155443322',
    email: 'budi.raharjo@sman1bdg.sch.id',
    subject: 'Bahasa Inggris',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't-4',
    name: 'Siti Aminah, S.Si.',
    nip: '198509302011012012',
    phone: '085722119988',
    email: 'siti.aminah@sman1bdg.sch.id',
    subject: 'Kimia',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't-5',
    name: 'Ahmad Fauzi, S.Kom.',
    nip: '198902182015041002',
    phone: '089677889900',
    email: 'ahmad.fauzi@sman1bdg.sch.id',
    subject: 'Informatika',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_CLASSES: Class[] = [
  {
    id: 'c-1',
    name: 'Kelas X-1',
    code: 'X-1',
    quota: 36,
    regu: 'Regu 1 (Ki Hajar Dewantara)',
    floor: 1,
    room_number: 'Ruang 101',
    whatsapp_link: 'https://chat.whatsapp.com/ExampleGrupX1',
    qr_code_link: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://chat.whatsapp.com/ExampleGrupX1',
    teacher_id: 't-1',
    binkel_name: 'Kak Farhan (OSIS)',
    binkel_phone: '081234567890',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-2',
    name: 'Kelas X-2',
    code: 'X-2',
    quota: 36,
    regu: 'Regu 2 (Ki Hajar Dewantara)',
    floor: 1,
    room_number: 'Ruang 102',
    whatsapp_link: 'https://chat.whatsapp.com/ExampleGrupX2',
    qr_code_link: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://chat.whatsapp.com/ExampleGrupX2',
    teacher_id: 't-2',
    binkel_name: 'Kak Nabila (MPK)',
    binkel_phone: '081298765432',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-3',
    name: 'Kelas X-3',
    code: 'X-3',
    quota: 36,
    regu: 'Regu 3 (R.A. Kartini)',
    floor: 2,
    room_number: 'Ruang 201',
    whatsapp_link: 'https://chat.whatsapp.com/ExampleGrupX3',
    qr_code_link: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://chat.whatsapp.com/ExampleGrupX3',
    teacher_id: 't-3',
    binkel_name: 'Kak Satria (OSIS)',
    binkel_phone: '082155443322',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-4',
    name: 'Kelas X-4',
    code: 'X-4',
    quota: 36,
    regu: 'Regu 4 (R.A. Kartini)',
    floor: 2,
    room_number: 'Ruang 202',
    whatsapp_link: 'https://chat.whatsapp.com/ExampleGrupX4',
    qr_code_link: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://chat.whatsapp.com/ExampleGrupX4',
    teacher_id: 't-4',
    binkel_name: 'Kak Amanda (OSIS)',
    binkel_phone: '085722119988',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'c-5',
    name: 'Kelas X-5',
    code: 'X-5',
    quota: 36,
    regu: 'Regu 5 (Ir. Juanda)',
    floor: 1,
    room_number: 'Ruang 301',
    whatsapp_link: 'https://chat.whatsapp.com/ExampleGrupX5',
    qr_code_link: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://chat.whatsapp.com/ExampleGrupX5',
    teacher_id: 't-5',
    binkel_name: 'Kak Zidan (MPK)',
    binkel_phone: '089677889900',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 's-1',
    full_name: 'Aditya Nugraha',
    registration_number: 'MPLS-2026-001',
    nisn: '0098765431',
    nik: '3273012010100001',
    gender: 'L',
    birth_place: 'Bandung',
    birth_date: '2010-05-12',
    address: 'Jl. Dago No. 12, Coblong, Bandung',
    school_origin: 'SMPN 1 Bandung',
    phone: '081211112222',
    email: 'aditya.nugraha@gmail.com',
    parent_name: 'Heri Nugraha',
    class_id: 'c-1',
    status: 'Aktif',
    notes: 'Siswa berprestasi jalur akademik',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-2',
    full_name: 'Bella Rizky Amalia',
    registration_number: 'MPLS-2026-002',
    nisn: '0098765432',
    nik: '3273012010100002',
    gender: 'P',
    birth_place: 'Bandung',
    birth_date: '2010-08-22',
    address: 'Jl. Merdeka No. 45, Sumur Bandung, Bandung',
    school_origin: 'SMP Taruna Bakti',
    phone: '081322223333',
    email: 'bella.rizky@gmail.com',
    parent_name: 'Ahmad Fauzi',
    class_id: 'c-2',
    status: 'Aktif',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-3',
    full_name: 'Dimas Hanafi',
    registration_number: 'MPLS-2026-003',
    nisn: '0098765433',
    nik: '3273012010100003',
    gender: 'L',
    birth_place: 'Jakarta',
    birth_date: '2010-01-15',
    address: 'Komplek Antapani Indah Blok C-5, Bandung',
    school_origin: 'SMPN 2 Bandung',
    phone: '081233334444',
    email: 'dimas.hanafi@gmail.com',
    parent_name: 'Subagyo Hanafi',
    class_id: 'c-3',
    status: 'Aktif',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-4',
    full_name: 'Farah Sabila Putri',
    registration_number: 'MPLS-2026-004',
    nisn: '0098765434',
    nik: '3273012010100004',
    gender: 'P',
    birth_place: 'Cimahi',
    birth_date: '2010-11-03',
    address: 'Jl. Cihanjuang No. 88, Cimahi Utara',
    school_origin: 'SMP Alfa Centauri',
    phone: '081344445555',
    email: 'farah.sabila@gmail.com',
    parent_name: 'Rudi Hermawan',
    class_id: 'c-1',
    status: 'Aktif',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-5',
    full_name: 'Gavin Rafif Pratama',
    registration_number: 'MPLS-2026-005',
    nisn: '0098765435',
    nik: '3273012010100005',
    gender: 'L',
    birth_place: 'Bandung',
    birth_date: '2010-06-30',
    address: 'Jl. Buah Batu No. 120, Lengkong, Bandung',
    school_origin: 'SMPN 5 Bandung',
    phone: '081255556666',
    email: 'gavin.rafif@gmail.com',
    parent_name: 'Tatang Pratama',
    class_id: 'c-4',
    status: 'Aktif',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-6',
    full_name: 'Hana Clarissa',
    registration_number: 'MPLS-2026-006',
    nisn: '0098765436',
    nik: '3273012010100006',
    gender: 'P',
    birth_place: 'Bandung',
    birth_date: '2010-09-18',
    address: 'Jl. Dr. Setiabudi No. 202, Cidadap, Bandung',
    school_origin: 'SMPN 12 Bandung',
    phone: '081366667777',
    email: 'hana.clara@gmail.com',
    parent_name: 'Wawan Clarissa',
    class_id: 'c-5',
    status: 'Aktif',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-7',
    full_name: 'Irfan Maulana',
    registration_number: 'MPLS-2026-007',
    nisn: '0098765437',
    nik: '3273012010100007',
    gender: 'L',
    birth_place: 'Tasikmalaya',
    birth_date: '2010-03-05',
    address: 'Jl. Kopo Sayati Gg. Haji Umar No. 4, Bandung',
    school_origin: 'SMPN 1 Tasikmalaya',
    phone: '081277778888',
    email: 'irfan.maulana@gmail.com',
    parent_name: 'Asep Maulana',
    class_id: 'c-2',
    status: 'Cadangan',
    notes: 'Menunggu konfirmasi daftar ulang berkas fisik',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 's-8',
    full_name: 'Kezia Aurelia',
    registration_number: 'MPLS-2026-008',
    nisn: '0098765438',
    nik: '3273012010100008',
    gender: 'P',
    birth_place: 'Bandung',
    birth_date: '2010-07-14',
    address: 'Kopo Permai Blok J-10, Margahayu, Bandung',
    school_origin: 'SMP Kristen Yusuf',
    phone: '081388889999',
    email: 'kezia.aurelia@gmail.com',
    parent_name: 'Susanto Aurelia',
    class_id: 'c-3',
    status: 'Aktif',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'a-1',
    title: 'Tata Tertib Pelaksanaan MPLS SMAN 1 Bandung Tahun Ajaran 2026/2027',
    content: `Yth. Calon Peserta Didik Baru SMAN 1 Bandung,\n\nBerikut adalah beberapa hal penting mengenai tata tertib yang wajib dipatuhi selama kegiatan Masa Pengenalan Lingkungan Sekolah (MPLS) berlangsung:\n\n1. **Pakaian**: Menggunakan seragam sekolah asal (SMP/MTs) lengkap, rapi, bersih, dan memakai atribut sekolah asal.\n2. **Waktu**: Seluruh peserta wajib hadir di sekolah paling lambat pukul 06.45 WIB. Kegiatan dimulai tepat pukul 07.00 WIB.\n3. **Barang Bawaan**: Membawa alat tulis, buku catatan MPLS, bekal makan siang sehat, botol minum isi ulang (tumblr), obat-obatan pribadi jika memiliki riwayat penyakit tertentu.\n4. **Larangan**: Dilarang membawa kendaraan bermotor, senjata tajam, rokok/vape, dan barang berharga berlebihan.\n\nHarap dipatuhi demi kelancaran bersama. Terima kasih.\n\n-- Panitia MPLS SMAN 1 Bandung`,
    status: 'Published',
    is_pinned: true,
    attachment_url: '#tata-tertib',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a-2',
    title: 'Panduan Pengisian Data & Gabung Grup WhatsApp Kelas X',
    content: `Halo Peserta Didik Baru!\n\nUntuk mempermudah koordinasi selama MPLS, mohon ikuti langkah-langkah berikut setelah menemukan kelas Anda:\n\n1. Cari nama Anda di kolom pencarian di halaman utama menggunakan Nomor NISN Anda.\n2. Lihat nama regu, kelas, ruangan, dan nama Wali Kelas Anda.\n3. Klik tombol **Gabung Grup WhatsApp** yang tertera di kartu detail siswa Anda untuk langsung masuk ke WhatsApp Grup koordinasi kelas.\n4. Hubungi Wali Kelas jika Anda menemui kendala.\n\nSelamat bergabung di keluarga besar SMAN 1 Bandung!`,
    status: 'Published',
    is_pinned: false,
    attachment_url: '#panduan-mpls',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'a-3',
    title: 'Informasi Pembagian Buku Paket dan Seragam Olahraga',
    content: `Diumumkan kepada seluruh siswa baru kelas X, bahwa pengambilan seragam olahraga dan buku paket pelajaran akan dilaksanakan secara terjadwal setelah upacara pembukaan MPLS pada hari Senin depan. Detail jadwal per kelas akan dibagikan oleh Wali Kelas masing-masing di grup WhatsApp kelas.`,
    status: 'Draft',
    is_pinned: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_FAQS: FAQ[] = [
  {
    id: 'faq-1',
    question: 'Bagaimana cara mengetahui kelas saya?',
    answer: 'Silakan masukkan 10 digit Nomor NISN Anda pada form pencarian di halaman depan. Sistem akan menampilkan nama regu, kelas, ruang, dan wali kelas Anda secara lengkap.',
    order_num: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'faq-2',
    question: 'Bagaimana jika nama saya belum terdaftar di kelas manapun?',
    answer: 'Jika Anda telah dinyatakan diterima di SMAN 1 Bandung namun data kelas tidak ditemukan, mohon segera hubungi Panitia MPLS melalui nomor hotline yang tertera di bagian bawah website ini dengan mengirimkan bukti tanda terima kelulusan.',
    order_num: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'faq-3',
    question: 'Apakah wajib bergabung dengan grup WhatsApp kelas?',
    answer: 'Ya, sangat wajib. Seluruh informasi teknis harian, penugasan MPLS, serta koordinasi dengan Wali Kelas akan disampaikan secara langsung melalui grup WhatsApp kelas masing-masing.',
    order_num: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'faq-4',
    question: 'Di mana saya bisa mengunduh Buku Panduan MPLS?',
    answer: 'Buku Panduan MPLS dan Tata Tertib dapat diunduh langsung melalui tombol "Download Panduan MPLS" dan "Download Tata Tertib" yang muncul di hasil pencarian Anda, atau di bagian bawah landing page.',
    order_num: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_SETTINGS: Setting = {
  school_name: 'SMAN 1 Bandung',
  school_logo: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&q=80&w=200',
  school_banner: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=1200',
  school_banners: [
    'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=1200',
    'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=1200',
    'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&q=80&w=1200'
  ],
  mpls_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 hari lagi
  committee_phone: '087778358755',
  status_publish: true,
  color_theme: 'modern-bento',
  guidebook_url: '#',
  rules_url: '#',
  embed_type: 'none',
  embed_code: '',
  certificate_template_url: '',
  is_certificate_published: false,
  certificate_name_x: 50,
  certificate_name_y: 42,
  certificate_name_size: 48,
  certificate_name_color: '#FFFFFF',
  certificate_name_font: 'sans-serif',
  certificate_name_bold: true,
  certificate_name_italic: false,
  certificate_name_uppercase: true
};

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    user_email: 'aminulloh18@gmail.com',
    action: 'Inisialisasi Sistem',
    details: 'Sistem Portal MPLS SMAN 1 Bandung berhasil dijalankan dengan database hybrid.',
    ip_address: '127.0.0.1',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'log-2',
    user_email: 'aminulloh18@gmail.com',
    action: 'Seeding Data Awal',
    details: 'Berhasil melakukan import 5 wali kelas dan 5 kelas utama.',
    ip_address: '127.0.0.1',
    created_at: new Date(Date.now() - 3600000 * 1.8).toISOString(),
  },
  {
    id: 'log-3',
    user_email: 'aminulloh18@gmail.com',
    action: 'Seeding Siswa',
    details: 'Berhasil memetakan 8 siswa awal ke dalam kelas masing-masing.',
    ip_address: '127.0.0.1',
    created_at: new Date(Date.now() - 3600000 * 1.5).toISOString(),
  }
];
